#!/usr/bin/env bash
set -euo pipefail
TARGET="${1:-streetpack_dock.py}"
[[ -f "$TARGET" ]] || { echo "ERR: target not found: $TARGET" >&2; exit 2; }

STAMP="$(date -u +%Y%m%d_%H%M%S_%3NZ 2>/dev/null || date -u +%Y%m%d_%H%M%SZ)"
BAK="${TARGET}.bak.${STAMP}"
cp -a -- "$TARGET" "$BAK"
TMP="${TARGET}.tmp.${STAMP}"

awk '
BEGIN{skip=0; injected=0}
# drop older canon blocks (any version)
(/^# SP_CTX_HANDLERS_CANON_V/){ skip=1; next }
(skip==1 && /^# END SP_CTX_HANDLERS_CANON_V/){ skip=0; next }
(skip==1){ next }

# inject just before class App so handlers exist early
(!injected && $0 ~ /^class[ \t]+App\b/){
  injected=1
  print "# SP_CTX_HANDLERS_CANON_V4  (receipts/outputs: open in text editor; right-click menu; robust path resolve)"
  print "import os, shlex, subprocess, shutil"
  print "from pathlib import Path"
  print ""
  print "def _sp__debug(msg):"
  print "    if os.environ.get(\"SP_DEBUG\", \"\").strip():"
  print "        try: print(msg, flush=True)"
  print "        except Exception: pass"
  print ""
  print "def _sp__share_root():"
  print "    xdg = os.environ.get(\"XDG_DATA_HOME\")"
  print "    base = Path(xdg) if xdg else (Path.home() / \".local/share\")"
  print "    return base / \"streetpack\""
  print ""
  print "def _sp__receipts_root(): return _sp__share_root() / \"receipts\""
  print "def _sp__outputs_root():  return _sp__share_root() / \"outputs\""
  print ""
  print "def _sp__pick_editor_cmd():"
  print "    env = os.environ.get(\"SP_EDITOR\", \"\").strip()"
  print "    if env:"
  print "        try: return shlex.split(env)"
  print "        except Exception: return [env]"
  print "    for c in (\"gnome-text-editor\",\"gedit\",\"kate\",\"mousepad\",\"xed\",\"code\"):"
  print "        p = shutil.which(c)"
  print "        if p:"
  print "            if c == \"code\": return [p, \"--reuse-window\"]"
  print "            return [p]"
  print "    return None"
  print ""
  print "def _sp__resolve(raw):"
  print "    if raw is None: return None"
  print "    s = str(raw).strip()"
  print "    if not s: return None"
  print "    s = s.split(\"|\", 1)[0].strip()"
  print "    p = Path(s)"
  print "    if p.is_absolute() and p.exists(): return p"
  print "    # direct under outputs/receipts"
  print "    for root in (_sp__outputs_root(), _sp__receipts_root()):"
  print "        cand = root / s"
  print "        if cand.exists(): return cand"
  print "    # receipts/<tool>/<file>"
  print "    rr = _sp__receipts_root()"
  print "    try:"
  print "        for cand in rr.glob(\"*/\" + s):"
  print "            if cand.exists(): return cand"
  print "    except Exception: pass"
  print "    # outputs/<tool>/<file> (if you ever nest)"
  print "    orr = _sp__outputs_root()"
  print "    try:"
  print "        for cand in orr.glob(\"*/\" + s):"
  print "            if cand.exists(): return cand"
  print "    except Exception: pass"
  print "    # shallow search fallback (limited)"
  print "    for root in (_sp__outputs_root(), _sp__receipts_root()):"
  print "        try:"
  print "            i = 0"
  print "            for cand in root.rglob(s):"
  print "                if cand.exists(): return cand"
  print "                i += 1"
  print "                if i > 50: break"
  print "        except Exception: pass"
  print "    cand = Path.cwd() / s"
  print "    if cand.exists(): return cand"
  print "    return None"
  print ""
  print "def _sp_open_text_editor(pathlike):"
  print "    p = pathlike if isinstance(pathlike, Path) else _sp__resolve(pathlike)"
  print "    if not p or not p.exists():"
  print "        _sp__debug(f\"[sp] open_text_editor: missing raw={pathlike!r} resolved={str(p) if p else None}\")"
  print "        return"
  print "    cmd = _sp__pick_editor_cmd()"
  print "    if not cmd:"
  print "        # last resort (may open browser depending on mime assoc)"
  print "        subprocess.Popen([\"xdg-open\", str(p)])"
  print "        return"
  print "    silent = (os.environ.get(\"SP_DEBUG\", \"\").strip() == \"\")"
  print "    out = subprocess.DEVNULL if silent else None"
  print "    err = subprocess.DEVNULL if silent else None"
  print "    _sp__debug(f\"[sp] open_text_editor: cmd={cmd!r} path={str(p)!r}\")"
  print "    subprocess.Popen(cmd + [str(p)], stdout=out, stderr=err)"
  print ""
  print "def _sp_reveal(pathlike):"
  print "    p = pathlike if isinstance(pathlike, Path) else _sp__resolve(pathlike)"
  print "    if not p or not p.exists():"
  print "        _sp__debug(f\"[sp] reveal: missing raw={pathlike!r} resolved={str(p) if p else None}\")"
  print "        return"
  print "    folder = str(p.parent)"
  print "    _sp__debug(f\"[sp] reveal: folder={folder!r}\")"
  print "    subprocess.Popen([\"xdg-open\", folder], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)"
  print ""
  print "def _sp__sel_raw(widget):"
  print "    try:"
  print "        sel = widget.curselection()"
  print "        if not sel: return None"
  print "        return widget.get(sel[0])"
  print "    except Exception:"
  print "        return None"
  print ""
  print "def _sp_open_from_widget(e, widget):"
  print "    raw = _sp__sel_raw(widget)"
  print "    _sp__debug(f\"[sp] click: raw={raw!r}\")"
  print "    if raw: _sp_open_text_editor(raw)"
  print ""
  print "def _sp_popup_path_menu(e, widget):"
  print "    raw = _sp__sel_raw(widget)"
  print "    _sp__debug(f\"[sp] menu: raw={raw!r}\")"
  print "    if not raw: return"
  print "    import tkinter as _tk"
  print "    m = getattr(widget, \"_sp_ctx_menu\", None)"
  print "    if m is None:"
  print "        m = _tk.Menu(widget, tearoff=0)"
  print "        widget._sp_ctx_menu = m"
  print "    else:"
  print "        m.delete(0, \"end\")"
  print "    m.add_command(label=\"Open in Text Editor\", command=lambda r=raw: _sp_open_text_editor(r))"
  print "    m.add_command(label=\"Open Folder\",         command=lambda r=raw: _sp_reveal(r))"
  print "    m.add_separator()"
  print "    m.add_command(label=\"Copy Path\",           command=lambda r=raw: (widget.clipboard_clear(), widget.clipboard_append(str(_sp__resolve(r) or r))))"
  print "    try:"
  print "        m.tk_popup(e.x_root, e.y_root)"
  print "    finally:"
  print "        try: m.grab_release()"
  print "        except Exception: pass"
  print "# END SP_CTX_HANDLERS_CANON_V4"
  print ""
}
{ print }
END{
  if(!injected){
    print \"ERR: could not find class App to inject before\" > \"/dev/stderr\"
    exit 4
  }
}
' "$TARGET" > "$TMP"

mv -f -- "$TMP" "$TARGET"
python3 -m py_compile "$TARGET" && echo "OK: CANON_V4 installed (syntax clean)"
echo "Backup: $BAK"
