# ============================================================
# FILE: .github/workflows/python-package.yml
# Purpose: lowest-headache CI for StreetPack (build + optional tests)
# ============================================================
name: Python package (CI)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip + build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Install deps (optional)
        run: |
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Install package (editable)
        run: |
          python -m pip install -e .

      - name: Run tests (optional)
        run: |
          if [ -d tests ]; then python -m pip install pytest && pytest -q; else echo "No tests/ folder; skipping."; fi

      - name: Build sdist + wheel
        run: |
          python -m build
